name: 'Check out repo and run dev server'
runs:
    using: 'composite'
    steps:
        - name: Checkout repo
          uses: actions/checkout@v2

        - name: Setup node
          uses: actions/setup-node@v1
          with:
              node-version: 12

        - name: 📥 Download deps
          uses: bahmutov/npm-install@v1
          with:
              useLockFile: false

        - name: Set domain
          run: echo "127.0.0.1 localhost.paypal.com" | sudo tee -a /etc/hosts

        - name: Run server
          shell: bash
          run: |
              ((npm run dev:standalone 2>&1 & echo $! > pid.log) | tee server.log) &
              sleep 40
              error_count=$(grep -i error server.log | wc -l)
              echo "Errors Found: $error_count"
              if [[ $error_count -gt 0 ]]; then
                  echo "Exiting server"
                  kill $(<pid.log)
                  exit 1
              fi
