name: Compare Snapshot Tests
on:
    # allow for manual triggers
    workflow_dispatch: {}

    push:
        branches:
            - develop
            - release
        paths:
            # Generic
            - server/**
            - src/**
            - tests/functional/spec/*
            - tests/functional/spec/utils/**
            - utils/**
            # ignores all locales and content
            - '!server/locale/**'
            - '!src/components/modal/content/**'
            # US Specific
            - banners/US/**
            - modals/US/**
            # re-includes US locales and US content
            - server/locale/US/**
            - src/components/modal/content/US*/**
            - tests/functional/spec/US/**
    pull_request:
        paths:
            # Generic
            - server/**
            - src/**
            - tests/functional/spec/*
            - tests/functional/spec/utils/**
            - utils/**
            # ignores all locales and content
            - '!server/locale/**'
            - '!src/components/modal/content/**'
            # US Specific
            - banners/US/**
            - modals/US/**
            # re-includes US locales and US content
            - server/locale/US/**
            - src/components/modal/content/US*/**
            - tests/functional/spec/US/**

jobs:
    compareSnapshots:
        name: US
        # if: "!contains(github.event.head_commit.message, '[snapshots]')"
        if: "!contains(github.event.pull_request.labels.*.name, 'snapshots')"
        runs-on: ubuntu-latest
        strategy:
            matrix:
                testPathPattern: [banner/text, banner/flex, modal/calc, modal/base, custom]
                node: [12]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - name: 📥 Download deps
              uses: bahmutov/npm-install@v1
              with:
                  useLockFile: false

            - name: Set domain
              run: echo "127.0.0.1 localhost.paypal.com" | sudo tee -a /etc/hosts

            - name: Run server
              run: |
                  ((npm run dev:standalone 2>&1 & echo $! > pid.log) | tee server.log) &
                  sleep 40
                  error_count=$(grep -i error server.log | wc -l)
                  echo "Errors Found: $error_count"
                  if [[ $error_count -gt 0 ]]; then
                      echo "Exiting server"
                      kill $(<pid.log)
                      exit 1
                  fi

            - name: Compare US Snapshots - ${{ matrix.testPathPattern }}
              continue-on-error: true
              run: |
                  npm run test:func -- --testPathPattern spec/US/${{ matrix.testPathPattern }}

            - name: Collect Diffs and Upload to Imgur
              run: |
                  ./scripts/snapshot-tests/collect-diffs.sh
