name: Snapshot Comparison Tests
on:
    # allow for manual triggers
    workflow_dispatch: {}
    workflow_call: {}
    push:
        branches:
            - develop
    pull_request: {}

jobs:
    getMatrix:
        name: Get Matrix
        runs-on: ubuntu-latest
        outputs:
            locale: ${{ steps.setMatrix.outputs.locale }}
            testPathPattern: ${{ steps.setMatrix.outputs.testPathPattern }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - id: setMatrix
              run: |
                  echo "::set-output name=locale::$(cat ./.github/configs/locales.json | tr '\n' ' ')"
                  echo "::set-output name=testPathPattern::$(cat ./.github/configs/testPathPatterns.json | tr '\n' ' ')"

    compareSnapshots:
        name: Non-US
        runs-on: ubuntu-latest
        needs: getMatrix
        strategy:
            fail-fast: false
            matrix:
                locale: ${{ fromJSON(needs.getMatrix.outputs.locale) }}
                testPathPattern: ${{ fromJSON(needs.getMatrix.outputs.testPathPattern) }}
                node: [12]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - name: 📥 Download deps
              uses: bahmutov/npm-install@v1
              with:
                  useLockFile: false

            - name: Run server
              run: |
                  ./.github/scripts/runServer.sh

            - name: Compare Snapshots - ${{ matrix.locale }}/${{ matrix.testPathPattern }}
              continue-on-error: true
              run: |
                  path=spec/${{ matrix.locale }}/${{ matrix.testPathPattern }}
                  if [ -d $path ]
                  then
                      npm run test:func -- --testPathPattern $path
                  else
                      echo "$path does not exist"
                      exit 0
                  fi

            - name: Collect Diffs and Upload to Imgur
              run: |
                  ./scripts/snapshot-tests/collect-diffs.sh
