name: Snapshot Comparisons - US
on:
    # allow for manual triggers
    workflow_dispatch: {}

    push:
        branches:
            - develop
            - release
        paths:
            # Generic
            - server/**
            - src/**
            - tests/functional/spec/*
            - tests/functional/spec/utils/**
            - utils/**
            # ignores all locales and content
            - '!server/locale/**'
            - '!src/components/modal/content/**'
            # US Specific
            - banners/US/**
            - modals/US/**
            # re-includes US locales and US content
            - server/locale/US/**
            - src/components/modal/content/US*/**
            - tests/functional/spec/US/**
    pull_request:
        paths:
            # Generic
            - server/**
            - src/**
            - tests/functional/spec/*
            - tests/functional/spec/utils/**
            - utils/**
            # ignores all locales and content
            - '!server/locale/**'
            - '!src/components/modal/content/**'
            # US Specific
            - banners/US/**
            - modals/US/**
            # re-includes US locales and US content
            - server/locale/US/**
            - src/components/modal/content/US*/**
            - tests/functional/spec/US/**

jobs:
    compareSnapshots:
        name: US
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                # testPathPattern: [banner/text, banner/flex, modal/calc, modal/base, custom]
                testPathPattern: [banner/text, banner/flex]
        steps:
            - uses: ./.github/composites/runServer

            - name: Compare US Snapshots - ${{ matrix.testPathPattern }}
              continue-on-error: true
              run: |
                  npm run test:func -- --testPathPattern spec/US/${{ matrix.testPathPattern }}

            - name: Collect Diffs and Upload to Imgur
              run: |
                  ./scripts/snapshot-tests/collect-diffs.sh
