name: Snapshot Comparison Tests
on:
    # allow for manual triggers
    workflow_dispatch: {}
    workflow_call: {}
    push:
        branches:
            - develop
    pull_request: {}

jobs:
    getMatrix:
        name: Get Matrix
        runs-on: ubuntu-latest
        outputs:
            testPathPatterns: ${{ steps.setTestPathPatterns.outputs.testPathPatterns }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - id: setMatrix
              run: |
                  echo "::set-output name=matrix::$(cat ./.github/configs/matrix.json | tr '\n' ' ')"

            - id: setTestPathPatterns
              run: |
                  locales=$(echo "${{ join(fromJSON(steps.setMatrix.outputs.matrix).locales) }}" | tr ',' '\n')
                  groups=$(echo "${{ join(fromJSON(steps.setMatrix.outputs.matrix).groups) }}" | tr ',' '\n')
                  validTestPathPatterns=()

                  for locale in $locales
                  do
                    for group in $groups
                    do
                        if [ -f "${{ github.workspace }}/tests/functional/spec/$locale/$group.test.js" ]; then
                            validTestPathPatterns+=("$locale/$group")
                        fi
                    done
                  done

                  testPathPatternsJson=$(printf '"%s"', "${validTestPathPatterns[@]}")
                  testPathPatternsJson="[${testPathPatternsJson%?}]"

                  echo "::set-output name=testPathPatterns::$testPathPatternsJson"

    compareSnapshots:
        name: Compare Snapshots
        runs-on: ubuntu-latest
        needs: getMatrix
        strategy:
            fail-fast: false
            matrix:
                testPathPattern: ${{ fromJSON(needs.getMatrix.outputs.testPathPatterns) }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 12

            - name: 📥 Download deps
              uses: bahmutov/npm-install@v1
              with:
                  useLockFile: false

            - name: Run server
              run: |
                  ./.github/scripts/runServer.sh

            - name: Compare Snapshots - ${{ matrix.testPathPattern }}
              continue-on-error: true
              run: |
                  npm run test:func -- --testPathPattern "${{ matrix.testPathPattern }}"

            - name: Collect Diffs and Upload to Imgur
              run: |
                  ./scripts/snapshot-tests/collect-diffs.sh
