name: Snapshot Comparison Tests - Non-US
on:
    # allow for manual triggers
    workflow_dispatch: {}

    push:
        branches:
            - develop
            - release
        paths:
            # Generic
            - banners/**
            - modals/**
            - server/**
            - src/**
            - tests/functional/spec/*
            - tests/functional/spec/utils/**
            - utils/**
            # Exclude US Files
            - '!banners/US/**'
            - '!modals/US/**'
            - '!server/locale/US/**'
            - '!src/components/modal/content/US*/**'
            - '!tests/functional/spec/US/**'
    pull_request:
        paths:
            # Generic
            - banners/**
            - modals/**
            - server/**
            - src/**
            - tests/functional/spec/*
            - tests/functional/spec/utils/**
            - utils/**
            # Exclude US Files
            - '!banners/US/**'
            - '!modals/US/**'
            - '!server/locale/US/**'
            - '!src/components/modal/content/US*/**'
            - '!tests/functional/spec/US/**'

jobs:
    # TODO: use this to run files for any generic change that affects all locales.
    #       currently changedFiles will only trigger tests for locale-specific changes.
    # changedFiles:
    #     name: Get Changed Locales
    #     runs-on: ubuntu-latest
    #     outputs:
    #         locales: ${{ steps.filter.outputs.changes }}
    #     steps:
    #         - name: Checkout repo
    #           uses: actions/checkout@v2

    #         - name: Filter locale paths
    #           uses: dorny/paths-filter@v2
    #           id: filter
    #           with:
    #               filters: .github/locales.yml

    #         # if none of the filter paths match, another file was changed that affect all locales
    #         - name: Set paths to all locales if none were filtered
    #           if: steps.filter.outputs.changes == '[]'

    compareSnapshots:
        name: Non-US
        runs-on: ubuntu-latest
        # needs: changedFiles
        strategy:
            fail-fast: false
            matrix:
                # locale: ${{ fromJSON(needs.changedFiles.outputs.locales) }}
                locale: [DE, AU, FR, GB]
                node: [12]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - name: 📥 Download deps
              uses: bahmutov/npm-install@v1
              with:
                  useLockFile: false

            - name: Run server
              run: |
                  ./.github/scripts/runServer.sh

            - name: Compare Banner Snapshots - ${{ matrix.locale }}
              continue-on-error: true
              run: |
                  npm run test:func -- --testPathPattern spec/${{ matrix.locale }}/banner

            - name: Compare Modal Snapshot - ${{ matrix.locale }}
              continue-on-error: true
              run: |
                  npm run test:func -- --testPathPattern spec/${{ matrix.locale }}/modal

            - name: Collect Diffs and Upload to Imgur
              run: |
                  ./scripts/snapshot-tests/collect-diffs.sh
