name: Snapshot Comparisons - Non-US
on:
    # allow for manual triggers
    workflow_dispatch: {}

    push:
        branches:
            - develop
            - release
        paths:
            # Generic
            - banners/**
            - modals/**
            - server/**
            - src/**
            - tests/functional/spec/*
            - tests/functional/spec/utils/**
            - utils/**
            # Exclude US Files
            - '!banners/US/**'
            - '!modals/US/**'
            - '!server/locale/US/**'
            - '!src/components/modal/content/US*/**'
            - '!tests/functional/spec/US/**'
    pull_request:
        paths:
            # Generic
            - banners/**
            - modals/**
            - server/**
            - src/**
            - tests/functional/spec/*
            - tests/functional/spec/utils/**
            - utils/**
            # Exclude US Files
            - '!banners/US/**'
            - '!modals/US/**'
            - '!server/locale/US/**'
            - '!src/components/modal/content/US*/**'
            - '!tests/functional/spec/US/**'

jobs:
    compareSnapshots:
        name: Non-US
        runs-on: ubuntu-latest
        # needs: changedFiles
        strategy:
            fail-fast: false
            matrix:
                # locale: ${{ fromJSON(needs.changedFiles.outputs.locales) }}
                # locale: [DE, AU, FR, GB]
                locale: [AU]
        steps:
            - uses: ./.github/composites/runServer

            - name: Compare Banner Snapshots - ${{ matrix.locale }}
              continue-on-error: true
              run: |
                  npm run test:func -- --testPathPattern spec/${{ matrix.locale }}/banner

            - name: Compare Modal Snapshot - ${{ matrix.locale }}
              continue-on-error: true
              run: |
                  npm run test:func -- --testPathPattern spec/${{ matrix.locale }}/modal

            - name: Collect Diffs and Upload to Imgur
              run: |
                  ./scripts/snapshot-tests/collect-diffs.sh
