name: Snapshot Comparison Tests - US
on:
    # allow for manual triggers
    workflow_dispatch: {}
    workflow_call: {}
    push:
        branches:
            - develop
    pull_request: {}

jobs:
    getTestPathPatterns:
        name: Get Locales
        runs-on: ubuntu-latest
        outputs:
            testPathPattern: ${{ steps.setMatrix.outputs.testPathPattern }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - id: setMatrix
              run: echo "::set-output name=testPathPattern::$(cat ./.github/configs/usTestPathPatterns.json | tr '\n' ' ')"

    compareSnapshots:
        name: US
        runs-on: ubuntu-latest
        needs: getTestPathPatterns
        strategy:
            fail-fast: false
            matrix:
                testPathPattern: ${{ fromJSON(needs.getTestPathPatterns.outputs.testPathPattern) }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 12

            - name: 📥 Download deps
              uses: bahmutov/npm-install@v1
              with:
                  useLockFile: false

            - name: Run server
              run: |
                  ./.github/scripts/runServer.sh

            - name: Compare US Snapshots - ${{ matrix.testPathPattern }}
              continue-on-error: true
              run: |
                  npm run test:func -- --testPathPattern spec/US/${{ matrix.testPathPattern }}

            - name: Collect Diffs and Upload to Imgur
              run: |
                  ./scripts/snapshot-tests/collect-diffs.sh
