name: Snapshot Comparison Tests - US
on:
    # allow for manual triggers
    workflow_dispatch: {}

    push:
        branches:
            - develop
            - release
        paths:
            # Generic
            - server/**
            - src/**
            - tests/functional/spec/*
            - tests/functional/spec/utils/**
            - utils/**
            # ignores all locales and content
            - '!server/locale/**'
            - '!src/components/modal/content/**'
            # US Specific
            - banners/US/**
            - modals/US/**
            # re-includes US locales and US content
            - server/locale/US/**
            - src/components/modal/content/US*/**
            - tests/functional/spec/US/**
    pull_request:
        paths:
            # Generic
            - server/**
            - src/**
            - tests/functional/spec/*
            - tests/functional/spec/utils/**
            - utils/**
            # ignores all locales and content
            - '!server/locale/**'
            - '!src/components/modal/content/**'
            # US Specific
            - banners/US/**
            - modals/US/**
            # re-includes US locales and US content
            - server/locale/US/**
            - src/components/modal/content/US*/**
            - tests/functional/spec/US/**

jobs:
    getTestPathPatterns:
        name: Get Locales
        if: contains(github.event.pull_request.labels.*.name, 'snapshots')
        runs-on: ubuntu-latest
        outputs:
            testPathPattern: ${{ steps.setMatrix.outputs.testPathPattern }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - id: setMatrix
              run: echo "::set-output name=testPathPattern::$(cat ./.github/usTestPathPatterns.json | tr '\n' ' ')"

    compareSnapshots:
        name: US
        runs-on: ubuntu-latest
        needs: getTestPathPatterns
        strategy:
            fail-fast: false
            matrix:
                testPathPattern: ${{ fromJSON(needs.getTestPathPatterns.outputs.testPathPattern) }}
                node: [12]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - name: 📥 Download deps
              uses: bahmutov/npm-install@v1
              with:
                  useLockFile: false

            - name: Run server
              run: |
                  ./.github/scripts/runServer.sh

            - name: Compare US Snapshots - ${{ matrix.testPathPattern }}
              continue-on-error: true
              run: |
                  npm run test:func -- --testPathPattern spec/US/${{ matrix.testPathPattern }}

            - name: Collect Diffs and Upload to Imgur
              run: |
                  ./scripts/snapshot-tests/collect-diffs.sh
