name: Compare Snapshots
on:
    # allow for manual triggers
    workflow_dispatch: {}
    workflow_call: {}
    push:
        branches:
            - develop
    pull_request: {}

jobs:
    getMatrix:
        name: Get Matrix
        runs-on: ubuntu-latest
        outputs:
            testPathPatterns: ${{ steps.setTestPathPatterns.outputs.testPathPatterns }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - id: setTestPathPatterns
              name: Set test path patterns
              run: |
                  validTestPaths=$(ls ./tests/functional/spec/*/*/*.test.js | sed -E 's/(.*spec\/|.test.js)//g')
                  testPathPatterns="[ \"$(echo $validTestPaths | tr '\n' ',' | sed 's/,$//' | sed 's/,/","/g' )\" ]"
                  echo "from yaml"
                  echo $validTestPaths | sed -z 's/\n/,/g'
                  echo
                  echo $validTestPaths | sed -z 's/\n/,/g;s/,$//'
                  echo
                  echo $validTestPaths | sed -z 's/\n/","/g'
                  echo
                  echo $validTestPaths | tr '\n' ','
                  echo
                  echo $validTestPaths | tr '\n' ',' | sed 's/,/","/g'
                  echo
                  echo $testPathPatterns
                  echo
                  echo "from script"
                  ./.github/scripts/getTestPathPatterns.sh
                  echo "::set-output name=testPathPatterns::$(./.github/scripts/getTestPathPatterns.sh)"

    compareSnapshots:
        name: Compare
        runs-on: ubuntu-latest
        needs: getMatrix
        strategy:
            fail-fast: false
            matrix:
                testPathPattern: ${{ fromJSON(needs.getMatrix.outputs.testPathPatterns) }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 12

            - name: 📥 Download deps
              uses: bahmutov/npm-install@v1
              with:
                  useLockFile: false

            - name: Run server
              run: |
                  ./.github/scripts/runServer.sh

            - name: Compare Snapshots - ${{ matrix.testPathPattern }}
              continue-on-error: true
              run: |
                  npm run test:func -- --testPathPattern "${{ matrix.testPathPattern }}"

            - name: Collect Diffs and Upload to Imgur
              run: |
                  ./scripts/snapshot-tests/collect-diffs.sh
