name: Update Snapshots
on:
    # allow for manual triggers
    workflow_dispatch: {}
    pull_request:
        types: [labeled]

jobs:
    getMatrix:
        name: Get Matrix
        if: github.event.label.name == 'snapshots' || github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        outputs:
            locale: ${{ steps.setMatrix.outputs.locale }}
            testPathPattern: ${{ steps.setMatrix.outputs.testPathPattern }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - id: setMatrix
              run: |
                  echo "::set-output name=locale::$(cat ./.github/configs/locales.json | tr '\n' ' ')"
                  echo "::set-output name=testPathPattern::$(cat ./.github/configs/testPathPatterns.json | tr '\n' ' ')"

    captureMetadata:
        name: Capture Metadata
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        needs: getMatrix
        steps:
            - name: Capture PR Number
              run: |
                  mkdir -p ./workflow/metadata
                  echo ${{ github.event.number }} > ./workflow/metadata/pull_number.txt

            - name: Save Metadata
              uses: actions/upload-artifact@v2
              with:
                  name: metadata
                  path: workflow/metadata/

    updateSnapshots:
        name: Non-US
        runs-on: ubuntu-latest
        needs: getMatrix
        strategy:
            matrix:
                locale: ${{ fromJSON(needs.getMatrix.outputs.locale) }}
                testPathPattern: ${{ fromJSON(needs.getMatrix.outputs.testPathPattern) }}
                node: [12]
        steps:
            - uses: hmarr/debug-action@v2

            - name: machine echo github
              env: { CONTENT: '${{ toJson(github) }}' }
              run: 'echo $CONTENT'

            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - name: 📥 Download deps
              uses: bahmutov/npm-install@v1
              with:
                  useLockFile: false

            - name: Run server
              run: |
                  ./.github/scripts/runServer.sh

            - name: Update Snapshots - ${{ matrix.locale }}/${{ matrix.testPathPattern }}
              run: |
                  path=spec/${{ matrix.locale }}/${{ matrix.testPathPattern }}
                  if [ -d $path ]
                  then
                      npm run test:func:ciupdate -- --testPathPattern $path
                  else
                      echo "$path does not exist"
                      exit 0
                  fi
                  git status --porcelain

            - name: Format Artifact Inputs
              id: artifactInputs
              run: |
                  if [ -z "$(git status --porcelain)" ]
                  then
                      echo "::set-output name=skip::true"
                      exit 0
                  fi

                  ARTIFACT_NAME="snapshot-$(sed 's/\//-/g' <<< '${{ matrix.locale }}')"
                  echo "::set-output name=name::$ARTIFACT_NAME"

                  ARTIFACT_PATH="snapshots/"
                  echo "::set-output name=path::$ARTIFACT_PATH"

                  UPDATED_SNAPSHOTS=$(git status --porcelain | grep 'snapshots' | sed -E "s/^.{3}//")
                  echo "$UPDATED_SNAPSHOTS" | while read -r path
                  do
                      newpath=$(echo $path | sed -E "s/^.+(snapshots.+)$/\\1/")
                      newdir=$(echo $newpath | sed -E "s/^(.+\/)[^\/]+$/\\1/")

                      mkdir -p "${{ github.workspace }}/$newdir"
                      mv "${{ github.workspace }}/$path" "${{ github.workspace }}/$newpath"
                  done

            - name: Save Snapshot Artifact
              if: steps.artifactInputs.outputs.skip != 'true'
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ steps.artifactInputs.outputs.name }}
                  path: ${{ steps.artifactInputs.outputs.path }}
                  retention-days: 1
