name: Update Snapshots
on:
    # allow for manual triggers
    workflow_dispatch: {}

    pull_request_target:
        types: [labeled]

    push:
        branches:
            - develop
            - release
        paths:
            # Generic
            - banners/**
            - modals/**
            - server/**
            - src/**
            - tests/functional/spec/*
            - tests/functional/spec/utils/**
            - utils/**
            # Exclude US Files
            - '!banners/US/**'
            - '!modals/US/**'
            - '!server/locale/US/**'
            - '!src/components/modal/content/US*/**'
            - '!tests/functional/spec/US/**'
    pull_request:
        paths:
            # Generic
            - banners/**
            - modals/**
            - server/**
            - src/**
            - tests/functional/spec/*
            - tests/functional/spec/utils/**
            - utils/**
            # Exclude US Files
            - '!banners/US/**'
            - '!modals/US/**'
            - '!server/locale/US/**'
            - '!src/components/modal/content/US*/**'
            - '!tests/functional/spec/US/**'

jobs:
    updateSnapshots:
        name: Non-US
        # if: contains(github.event.head_commit.message, '[snapshots]')
        if: contains(github.event.pull_request.labels.*.name, 'snapshots')
        runs-on: ubuntu-latest
        strategy:
            matrix:
                locale: [DE, AU, FR, GB]
                node: [12]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - name: 📥 Download deps
              uses: bahmutov/npm-install@v1
              with:
                  useLockFile: false

            - name: Set domain
              run: echo "127.0.0.1 localhost.paypal.com" | sudo tee -a /etc/hosts

            - name: Run server
              run: |
                  ((npm run dev:standalone 2>&1 & echo $! > pid.log) | tee server.log) &
                  sleep 40
                  error_count=$(grep -i error server.log | wc -l)
                  echo "Errors Found: $error_count"
                  if [[ $error_count -gt 0 ]]; then
                      echo "Exiting server"
                      kill $(<pid.log)
                      exit 1
                  fi

            - name: Update Banner Snapshots - ${{ matrix.locale }}
              run: |
                  npm run test:func:ciupdate -- --testPathPattern spec/${{ matrix.locale }}/banner
                  git status

            - name: Update Modal Snapshots - ${{ matrix.locale }}
              run: |
                  npm run test:func:ciupdate -- --testPathPattern spec/${{ matrix.locale }}/modal
                  git status

            - name: Commit Updated Snapshots - ${{ matrix.locale }}
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: 'chore(snapshots): update ${{ matrix.locale }} snapshots [skip ci]'
                  commit_options: '--no-verify --quiet'
                  commit_user_name: Snapshot Actions Bot
                  file_pattern: tests/functional/snapshots/
                  push_options: '-v'
