name: Update Snapshots - US
on:
    # allow for manual triggers
    workflow_dispatch: {}
    pull_request: {}
    pull_request_target:
        types: [labeled]

jobs:
    updateSnapshots:
        name: US
        # if: contains(github.event.head_commit.message, '[snapshots]')
        if: contains(github.event.pull_request.labels.*.name, 'snapshots')
        runs-on: ubuntu-latest
        strategy:
            matrix:
                # testPathPattern: [banner/text, banner/flex, modal/calc, modal/base, custom]
                testPathPattern: [banner/text, banner/flex]
        steps:
            - uses: ./.github/composites/runServer

            - name: Update US Snapshots
              run: |
                  npm run test:func:ciupdate -- --testPathPattern spec/US/${{ matrix.testPathPattern }}
                  git status

            - name: Commit Updated Snapshots - US Modal
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: 'chore(snapshots): update US modal snapshots [skip ci]'
                  commit_options: '--no-verify --quiet'
                  commit_user_name: Snapshot Actions Bot
                  file_pattern: tests/functional/snapshots/US/*/modal
                  push_options: '-v'

            - name: Commit Updated Snapshots - US Banner and Custom
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: 'chore(snapshots): update US banner and custom snapshots [skip ci]'
                  commit_options: '--no-verify --quiet'
                  commit_user_name: Snapshot Actions Bot
                  # no need to specify flex, text, or custom since modal files were already committed
                  file_pattern: tests/functional/snapshots/US/
                  push_options: '-v'
