name: Update Snapshots - Non-US
on:
    # allow for manual triggers
    workflow_dispatch: {}
    pull_request: {}
    pull_request_target:
        types: [labeled]

jobs:
    updateSnapshots:
        name: Non-US
        # if: contains(github.event.head_commit.message, '[snapshots]')
        if: contains(github.event.pull_request.labels.*.name, 'snapshots')
        runs-on: ubuntu-latest
        strategy:
            matrix:
                # locale: [DE, AU, FR, GB]
                locale: [AU]
        steps:
            - uses: ./.github/composites/runServer

            - name: Update Banner Snapshots - ${{ matrix.locale }}
              run: |
                  npm run test:func:ciupdate -- --testPathPattern spec/${{ matrix.locale }}/banner
                  git status

            - name: Update Modal Snapshots - ${{ matrix.locale }}
              run: |
                  npm run test:func:ciupdate -- --testPathPattern spec/${{ matrix.locale }}/modal
                  git status

            - name: Commit Updated Snapshots - ${{ matrix.locale }}
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: 'chore(snapshots): update ${{ matrix.locale }} snapshots [skip ci]'
                  commit_options: '--no-verify --quiet'
                  commit_user_name: Snapshot Actions Bot
                  file_pattern: tests/functional/snapshots/
                  push_options: '-v'
